STATUS_DATA = {
    # 1xx – Informativo - ok
    100: {"nome": "Continue", "descricao": "O servidor recebeu parte da requisição e o cliente deve continuar.", "imagem": "100.jpg"},
    101: {"nome": "Switching Protocols", "descricao": "O servidor está mudando os protocolos conforme solicitado.", "imagem": "101.jpg"},
    102: {"nome": "Processing", "descricao": "O servidor está processando o pedido, mas ainda não tem resposta.", "imagem": "102.jpg"},
    103: {"nome": "Early Hints", "descricao": "Fornece cabeçalhos antecipadamente para melhorar o carregamento.", "imagem": "103.jpg"},

    # 2xx – Sucesso - ok
    200: {"nome": "OK", "descricao": "Requisição bem-sucedida. Tudo ocorreu corretamente.", "imagem": "200.jpg"},
    201: {"nome": "Created", "descricao": "O recurso foi criado com sucesso.", "imagem": "201.jpg"},
    202: {"nome": "Accepted", "descricao": "A requisição foi aceita para processamento, mas ainda não concluída.", "imagem": "202.jpg"},
    203: {"nome": "Non-Authoritative Information", "descricao": "A resposta foi retornada com informações de terceiros.", "imagem": "203.jpg"},
    204: {"nome": "No Content", "descricao": "A requisição foi bem-sucedida, mas não há conteúdo a retornar.", "imagem": "204.jpg"},
    205: {"nome": "Reset Content", "descricao": "O cliente deve redefinir a visualização do documento.", "imagem": "205.jpg"},
    206: {"nome": "Partial Content", "descricao": "O servidor está enviando apenas parte do recurso solicitado.", "imagem": "206.jpg"},
    207: {"nome": "Multi-Status", "descricao": "Vários status são retornados para diferentes operações.", "imagem": "207.jpg"},
    208: {"nome": "Already Reported", "descricao": "O recurso já foi reportado anteriormente.", "imagem": "208.jpg"},
    226: {"nome": "IM Used", "descricao": "O servidor cumpriu uma requisição com uma resposta delta (instância modificada).", "imagem": "226.jpg"},

    # 3xx – Redirecionamento - ok
    300: {"nome": "Multiple Choices", "descricao": "Há várias opções para o recurso solicitado.", "imagem": "300.jpg"},
    301: {"nome": "Moved Permanently", "descricao": "O recurso foi movido permanentemente para outro local.", "imagem": "301.jpg"},
    302: {"nome": "Found", "descricao": "O recurso foi encontrado em outro local temporariamente.", "imagem": "302.jpg"},
    303: {"nome": "See Other", "descricao": "O recurso deve ser acessado por meio de outra URL.", "imagem": "303.jpg"},
    304: {"nome": "Not Modified", "descricao": "O recurso não foi modificado desde a última requisição.", "imagem": "304.jpg"},
    305: {"nome": "Use Proxy", "descricao": "O recurso deve ser acessado através de um proxy.", "imagem": "305.jpg"},
    306: {"nome": "Switch Proxy", "descricao": "Código obsoleto. Não é mais utilizado.", "imagem": "306.jpg"},
    307: {"nome": "Temporary Redirect", "descricao": "O recurso foi movido temporariamente para outro local.", "imagem": "307.jpg"},
    308: {"nome": "Permanent Redirect", "descricao": "O recurso foi movido permanentemente para outra URL.", "imagem": "308.jpg"},

    # 4xx – Erros do cliente
    400: {"nome": "Bad Request", "descricao": "A requisição está incorreta ou malformada.", "imagem": "400.jpg"},
    401: {"nome": "Unauthorized", "descricao": "Autenticação necessária para acessar o recurso.", "imagem": "401.jpg"},
    402: {"nome": "Payment Required", "descricao": "Pagamento necessário para acessar o recurso.", "imagem": "402.jpg"},
    403: {"nome": "Forbidden", "descricao": "Acesso proibido ao recurso solicitado.", "imagem": "403.jpg"},
    404: {"nome": "Not Found", "descricao": "O recurso solicitado não foi encontrado.", "imagem": "404.jpg"},
    405: {"nome": "Method Not Allowed", "descricao": "O método HTTP usado não é permitido para este recurso.", "imagem": "405.jpg"},
    406: {"nome": "Not Acceptable", "descricao": "O servidor não pode fornecer uma resposta aceitável.", "imagem": "406.jpg"},
    407: {"nome": "Proxy Authentication Required", "descricao": "Autenticação no proxy é necessária.", "imagem": "407.jpg"},
    408: {"nome": "Request Timeout", "descricao": "O tempo de requisição expirou.", "imagem": "408.jpg"},
    409: {"nome": "Conflict", "descricao": "Há um conflito na requisição, como dados duplicados.", "imagem": "409.jpg"},
    410: {"nome": "Gone", "descricao": "O recurso solicitado não está mais disponível.", "imagem": "410.jpg"},
    411: {"nome": "Length Required", "descricao": "O cabeçalho Content-Length é obrigatório.", "imagem": "411.jpg"},
    412: {"nome": "Precondition Failed", "descricao": "Uma condição prévia na requisição falhou.", "imagem": "412.jpg"},
    413: {"nome": "Payload Too Large", "descricao": "O corpo da requisição é muito grande.", "imagem": "413.jpg"},
    414: {"nome": "URI Too Long", "descricao": "A URI fornecida é muito longa.", "imagem": "414.jpg"},
    415: {"nome": "Unsupported Media Type", "descricao": "O tipo de mídia não é suportado pelo servidor.", "imagem": "415.jpg"},
    416: {"nome": "Range Not Satisfiable", "descricao": "A faixa solicitada não pode ser atendida.", "imagem": "416.jpg"},
    417: {"nome": "Expectation Failed", "descricao": "A expectativa definida no cabeçalho Expect falhou.", "imagem": "417.jpg"},
    418: {"nome": "I'm a teapot", "descricao": "Sou um bule de chá. (Piada do HTTP 418).", "imagem": "418.jpg"},
    421: {"nome": "Misdirected Request", "descricao": "A requisição foi enviada a um servidor errado.", "imagem": "421.jpg"},
    422: {"nome": "Unprocessable Entity", "descricao": "O servidor entende o conteúdo, mas não pode processá-lo.", "imagem": "422.jpg"},
    423: {"nome": "Locked", "descricao": "O recurso está bloqueado.", "imagem": "423.jpg"},
    424: {"nome": "Failed Dependency", "descricao": "Uma operação falhou devido à dependência de outra.", "imagem": "424.jpg"},
    425: {"nome": "Too Early", "descricao": "O servidor não quer processar a requisição antecipadamente.", "imagem": "425.jpg"},
    426: {"nome": "Upgrade Required", "descricao": "O cliente deve atualizar para outro protocolo.", "imagem": "426.jpg"},
    428: {"nome": "Precondition Required", "descricao": "Requisição precisa de uma condição prévia.", "imagem": "428.jpg"},
    429: {"nome": "Too Many Requests", "descricao": "O cliente enviou muitas requisições em pouco tempo.", "imagem": "429.jpg"},
    431: {"nome": "Request Header Fields Too Large", "descricao": "Os campos de cabeçalho são muito grandes.", "imagem": "431.jpg"},
    451: {"nome": "Unavailable For Legal Reasons", "descricao": "O conteúdo está indisponível por razões legais.", "imagem": "451.jpg"},

    # 5xx – Erros do servidor
    500: {"nome": "Internal Server Error", "descricao": "Erro interno no servidor.", "imagem": "500.jpg"},
    501: {"nome": "Not Implemented", "descricao": "O servidor não reconhece ou não suporta o método.", "imagem": "501.jpg"},
    502: {"nome": "Bad Gateway", "descricao": "O servidor recebeu uma resposta inválida de outro servidor.", "imagem": "502.jpg"},
    503: {"nome": "Service Unavailable", "descricao": "O servidor está temporariamente indisponível.", "imagem": "503.jpg"},
    504: {"nome": "Gateway Timeout", "descricao": "O tempo de resposta do gateway expirou.", "imagem": "504.jpg"},
    505: {"nome": "HTTP Version Not Supported", "descricao": "A versão do HTTP não é suportada.", "imagem": "505.jpg"},
    506: {"nome": "Variant Also Negotiates", "descricao": "Erro de configuração de negociação de conteúdo.", "imagem": "506.jpg"},
    507: {"nome": "Insufficient Storage", "descricao": "O servidor não possui espaço para armazenar o recurso.", "imagem": "507.jpg"},
    508: {"nome": "Loop Detected", "descricao": "O servidor detectou um loop infinito ao processar a requisição.", "imagem": "508.jpg"},
    510: {"nome": "Not Extended", "descricao": "Extensões adicionais são necessárias para completar a requisição.", "imagem": "510.jpg"},
    511: {"nome": "Network Authentication Required", "descricao": "Autenticação de rede é necessária.", "imagem": "511.jpg"},
    521: {"nome": "Web Server Is Down", "descricao": "O servidor web está fora do ar.", "imagem": "521.jpg"},
    522: {"nome": "Connection Timed Out", "descricao": "A conexão expirou.", "imagem": "522.jpg"},
    523: {"nome": "Origin Is Unreachable", "descricao": "A origem está inacessível.", "imagem": "523.jpg"},
    525: {"nome": "SSL Handshake Failed", "descricao": "Falha no handshake SSL.", "imagem": "525.jpg"},
    530: {"nome": "Site Is Frozen", "descricao": "O site está congelado.", "imagem": "530.jpg"},    
    599: {"nome": "Network Connect Timeout Error", "descricao": "Erro de tempo limite na conexão de rede.", "imagem": "599.jpg"},
}
